#!/bin/bash
set -eo pipefail

# Prove ZKsyncOS Ethereum blocks with ZisK GPU prover
# Usage: ./prove-block-zisk.sh [BLOCK_NUMBER]
#
# Environment variables:
#   VERBOSE=1    Show detailed logging - operation counts, trace fills (default)
#   VERBOSE=2    Show debug-level logging (even more detail)
#   VERBOSE=0    Quiet mode - minimal output
#   REBUILD=1    Do incremental builds (default)
#   REBUILD=0    Skip all builds, just run the prover (for timing measurements)
#   CLEAN_GPU=1  Force clean and rebuild GPU libraries (use after proving key regen)
#
# This script proves Ethereum blocks using ZKsyncOS on the ZisK GPU prover.
# It uses a witness file generated by bench-zisk-cycles.sh to replay oracle data.
#
# The script always performs incremental builds to include any new changes:
# - ZKsyncOS ELF for ZisK (with delegation feature)
# - cargo-zisk binary with GPU support
# - libzisk_witness.so witness library
#
# Precompile Support:
# - U256 delegation (CSR 0x7ca): Enabled for BigInt arithmetic (ADD, SUB, MUL_LOW, MUL_HIGH, EQ, MEMCPY)
# - Keccak: Native support via CSR 0x800
#
# Prerequisites:
# - Download proving key (see book/building-for-gpu.md)
# - Block data in zksync-os/tests/instances/eth_runner/blocks/

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

# Set verbose flags based on VERBOSE env var (default: 1)
VERBOSE_FLAGS=""
if [[ "${VERBOSE:-1}" == "2" ]]; then
    VERBOSE_FLAGS="-vv"
elif [[ "${VERBOSE:-1}" == "1" ]]; then
    VERBOSE_FLAGS="-v"
fi
# VERBOSE=0 means no flags (quiet mode)

# Check if we should skip builds (default: 1 = do builds)
SKIP_BUILD=false
if [[ "${REBUILD:-1}" == "0" ]]; then
    SKIP_BUILD=true
fi

BLOCK_NUMBER="${1:-24198369}"
ZKSYNCOS_DIR="$REPO_ROOT/zksync-os"
ETH_RUNNER_DIR="$ZKSYNCOS_DIR/tests/instances/eth_runner"
ELF_FILE="$ZKSYNCOS_DIR/zksync_os/zksync_os_zisk.elf"
WITNESS_FILE="$ETH_RUNNER_DIR/${BLOCK_NUMBER}_witness"
OUTPUT_DIR="tmp/zisk-prove"

echo "=== ZisK GPU ZKsyncOS Proving Test ==="
echo "Block: $BLOCK_NUMBER"
echo "ELF: $ELF_FILE"
echo "Witness: $WITNESS_FILE"
echo "Output: $OUTPUT_DIR"
echo ""

# Build ZKsyncOS for ZisK (incremental)
# Features must match setup.sh for reproducibility
ZKSYNCOS_FEATURES="proving,print_debug_info,delegation,global-alloc,pectra,evm_refunds,unlimited_native,prevrandao,disable_system_contracts,zisk_keccak"
if [[ "$SKIP_BUILD" == "false" ]]; then
    echo "Building ZKsyncOS for ZisK (incremental)..."
    if ! (cd "$ZKSYNCOS_DIR/zksync_os" && FEATURES="$ZKSYNCOS_FEATURES" ./build.sh --machine zisk) 2>&1 | tee /tmp/zksyncos-build.log | tail -10; then
        echo "ERROR: Failed to build ZKsyncOS"
        echo "See /tmp/zksyncos-build.log for details"
        exit 1
    fi
    echo "ZKsyncOS build complete"
    echo ""
fi

# Verify ELF was created
if [[ ! -f "$ELF_FILE" ]]; then
    echo "ERROR: ZKsyncOS ELF not found at $ELF_FILE after build"
    exit 1
fi

# Check if witness file exists - generate if needed
if [[ ! -f "$WITNESS_FILE" ]]; then
    echo "Witness file not found. Running bench-zisk-cycles.sh to generate it..."
    echo ""
    ./bench-zisk-cycles.sh "$BLOCK_NUMBER"
    echo ""
    if [[ ! -f "$WITNESS_FILE" ]]; then
        echo "ERROR: Witness file still not found after running benchmark"
        exit 1
    fi
fi
echo "Witness file: $(ls -lh "$WITNESS_FILE" | awk '{print $5}')"
echo ""

# Source Intel OneAPI environment
if [[ -f /opt/intel/oneapi/setvars.sh ]]; then
    source /opt/intel/oneapi/setvars.sh > /dev/null 2>&1
fi

# Set up library paths for Intel OpenMP and Rust std
RUST_STD_PATH="$(rustc --print sysroot)/lib/rustlib/x86_64-unknown-linux-gnu/lib"
export LD_LIBRARY_PATH="$RUST_STD_PATH:/opt/intel/oneapi/compiler/2025.0/lib:${LD_LIBRARY_PATH:-}"
export LIBRARY_PATH="/opt/intel/oneapi/compiler/2025.0/lib:${LIBRARY_PATH:-}"

# Build prover and witness library (unless REBUILD=0)
PROVER_BINARY="./target/release/cargo-zisk"
WITNESS_LIB="./target/release/libzisk_witness.so"

# Check if GPU libraries exist in pil2-proofman cache
# If missing or CLEAN_GPU=1, clean and force rebuild
PIL2_STARK_DIR=$(find ~/.cargo/git/checkouts/pil2-proofman-* -maxdepth 2 -name "pil2-stark" -type d 2>/dev/null | head -1)
GPU_LIB_EXISTS=false
if [[ -n "$PIL2_STARK_DIR" && -d "$PIL2_STARK_DIR/lib-gpu" ]]; then
    GPU_LIB_EXISTS=true
fi

if [[ "${CLEAN_GPU:-0}" == "1" ]] || [[ "$GPU_LIB_EXISTS" == "false" ]]; then
    echo "Cleaning GPU libraries from pil2-proofman cache..."
    rm -rf ~/.cargo/git/checkouts/pil2-proofman-*/*/pil2-stark/lib-gpu 2>/dev/null || true
    rm -rf ~/.cargo/git/checkouts/pil2-proofman-*/*/pil2-stark/build-gpu 2>/dev/null || true
    # Force rebuild of proofman-starks-lib-c
    cargo clean -p proofman-starks-lib-c 2>/dev/null || true
    echo "GPU libraries cleaned - will rebuild"
    echo ""
fi

if [[ "$SKIP_BUILD" == "false" ]]; then
    echo "Building prover with GPU support (incremental)..."
    if ! cargo build --release --features gpu 2>&1 | tee /tmp/prover-build.log | tail -10; then
        echo "ERROR: Failed to build prover with GPU support"
        echo "See /tmp/prover-build.log for details"
        exit 1
    fi
    echo "Prover build complete"
    echo ""

    echo "Building witness library (incremental)..."
    if ! cargo build --release -p zisk-witness --lib 2>&1 | tee /tmp/witness-build.log | tail -5; then
        echo "ERROR: Failed to build witness library"
        echo "See /tmp/witness-build.log for details"
        exit 1
    fi
    echo "Witness library build complete"
    echo ""
else
    echo "Skipping builds (REBUILD=0)"
    echo ""
fi

# Run ROM setup (checks ELF hash against cached artifacts)
PROVING_KEY="${PROVING_KEY:-$REPO_ROOT/provingKey}"
if [[ -d "$PROVING_KEY" ]]; then
    echo "Running ROM setup (will skip if cache is current)..."
    if ! ./target/release/cargo-zisk rom-setup --elf "$ELF_FILE" --proving-key "$PROVING_KEY" 2>&1 | tee /tmp/rom-setup.log | tail -5; then
        echo "ERROR: ROM setup failed"
        echo "See /tmp/rom-setup.log for details"
        exit 1
    fi
    echo ""
fi

mkdir -p "$OUTPUT_DIR"

LOG_FILE="/tmp/prove-block-zisk.log"

# Build prover command
PROVER_CMD="./target/release/cargo-zisk prove \
    --elf $ELF_FILE \
    --witness-file $WITNESS_FILE \
    --witness-lib ./target/release/libzisk_witness.so \
    --proving-key ./provingKey \
    --output-dir $OUTPUT_DIR \
    --emulator \
    -r \
    -t 4"
if [[ -n "$VERBOSE_FLAGS" ]]; then
    PROVER_CMD="$PROVER_CMD $VERBOSE_FLAGS"
fi

# Run prover with appropriate output handling
if [[ "${VERBOSE:-1}" == "0" ]]; then
    # Quiet mode: suppress all output
    echo "Running ZisK GPU prover in quiet mode..."
    if $PROVER_CMD > /dev/null 2>&1; then
        echo "=== Proving SUCCEEDED ==="
    else
        EXIT_CODE=$?
        echo "=== Proving FAILED (exit code $EXIT_CODE) ==="
        echo "Re-run with VERBOSE=1 to see logs"
    fi
else
    # Normal/verbose mode: log to file
    echo "Running ZisK GPU prover (output in $LOG_FILE)..."
    echo ""
    if $PROVER_CMD > "$LOG_FILE" 2>&1; then
        echo "=== Proving SUCCEEDED ==="
        echo ""
        echo "Summary (last 20 lines of log):"
        echo "----------------------------------------"
        tail -20 "$LOG_FILE"
        echo "----------------------------------------"
        echo ""
        echo "Output: $OUTPUT_DIR/"
        ls -la "$OUTPUT_DIR/" 2>/dev/null || true
    else
        EXIT_CODE=$?
        echo "=== Proving FAILED (exit code $EXIT_CODE) ==="
        echo ""
        echo "Last 50 lines of log:"
        echo "----------------------------------------"
        tail -50 "$LOG_FILE"
        echo "----------------------------------------"
    fi
    echo ""
    echo "Full log: $LOG_FILE"
fi
