#!/bin/bash
set -e

# Prove ZKsyncOS Ethereum blocks with Airbender GPU prover
# Usage: ./prove-block-airbender.sh [BLOCK_NUMBER]
#
# Environment variables:
#   VERBOSE=1    Show detailed logging (default)
#   VERBOSE=2    Show debug-level logging (even more detail)
#   VERBOSE=0    Quiet mode - minimal output
#   REBUILD=1    Do incremental builds (default)
#   REBUILD=0    Skip all builds, just run the prover (for timing measurements)
#
# This script proves Ethereum blocks using ZKsyncOS on the Airbender GPU prover.
# It uses a witness file generated by bench-airbender-cycles.sh to replay oracle data.
#
# The script always performs incremental builds to include any new changes:
# - ZKsyncOS binary for Airbender (RV32IM)
# - Airbender CLI with GPU support
#
# Precompile Support:
# - U256 delegation (CSR 0x7ca): Enabled for BigInt arithmetic
# - Keccak delegation (CSR 0x7cb): Delegation to Keccak circuits
# - Blake2s delegation (CSR 0x7c7): Delegation to Blake2s circuits
#
# Prerequisites:
# - Block data in zksync-os/tests/instances/eth_runner/blocks/

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

# Set verbose flags based on VERBOSE env var (default: 1)
# Note: Airbender CLI doesn't have the same -v flags, but we track the setting
VERBOSE_LEVEL="${VERBOSE:-1}"

# Check if we should skip builds (default: 1 = do builds)
SKIP_BUILD=false
if [[ "${REBUILD:-1}" == "0" ]]; then
    SKIP_BUILD=true
fi

BLOCK_NUMBER="${1:-24198369}"
ZKSYNCOS_DIR="$REPO_ROOT/zksync-os"
AIRBENDER_DIR="$REPO_ROOT/zksync-airbender"
ETH_RUNNER_DIR="$ZKSYNCOS_DIR/tests/instances/eth_runner"
BIN_FILE="$ZKSYNCOS_DIR/zksync_os/zksync_os_airbender.bin"
TEXT_FILE="$ZKSYNCOS_DIR/zksync_os/zksync_os_airbender.text"
WITNESS_FILE="$ETH_RUNNER_DIR/${BLOCK_NUMBER}_witness"
OUTPUT_DIR="tmp/airbender-prove"

echo "=== Airbender GPU ZKsyncOS Proving Test ==="
echo "Block: $BLOCK_NUMBER"
echo "Binary: $BIN_FILE"
echo "Witness: $WITNESS_FILE"
echo "Output: $OUTPUT_DIR"
echo ""

# Build ZKsyncOS for Airbender (incremental)
ZKSYNCOS_FEATURES="proving,print_debug_info,global-alloc,pectra,evm_refunds,unlimited_native,prevrandao,disable_system_contracts"
if [[ "$SKIP_BUILD" == "false" ]]; then
    echo "Building ZKsyncOS for Airbender (incremental)..."
    if ! (cd "$ZKSYNCOS_DIR/zksync_os" && FEATURES="$ZKSYNCOS_FEATURES" ./build.sh --machine airbender) 2>&1 | tee /tmp/zksyncos-airbender-build.log | tail -10; then
        echo "ERROR: Failed to build ZKsyncOS for Airbender"
        echo "See /tmp/zksyncos-airbender-build.log for details"
        exit 1
    fi
    echo "ZKsyncOS build complete"
    echo ""
fi

# Verify binary was created
if [[ ! -f "$BIN_FILE" ]]; then
    echo "ERROR: ZKsyncOS binary not found at $BIN_FILE after build"
    exit 1
fi

# Check if witness file exists - generate if needed
if [[ ! -f "$WITNESS_FILE" ]]; then
    echo "Witness file not found. Running bench-airbender-cycles.sh to generate it..."
    echo ""
    ./bench-airbender-cycles.sh "$BLOCK_NUMBER"
    echo ""
    if [[ ! -f "$WITNESS_FILE" ]]; then
        echo "ERROR: Witness file still not found after running benchmark"
        exit 1
    fi
fi
echo "Witness file: $(ls -lh "$WITNESS_FILE" | awk '{print $5}')"
echo ""

# Build Airbender CLI with GPU support (unless REBUILD=0)
AIRBENDER_CLI="$AIRBENDER_DIR/target/release/cli"

if [[ "$SKIP_BUILD" == "false" ]]; then
    echo "Building Airbender CLI with GPU support (incremental)..."
    if ! (cd "$AIRBENDER_DIR" && cargo build -p cli --release --features gpu) 2>&1 | tee /tmp/airbender-cli-build.log | tail -10; then
        echo "ERROR: Failed to build Airbender CLI"
        echo "See /tmp/airbender-cli-build.log for details"
        exit 1
    fi
    echo "Airbender CLI build complete"
    echo ""
else
    echo "Skipping builds (REBUILD=0)"
    echo ""
fi

# Verify CLI was built
if [[ ! -f "$AIRBENDER_CLI" ]]; then
    echo "ERROR: Airbender CLI not found at $AIRBENDER_CLI"
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

LOG_FILE="/tmp/prove-block-airbender.log"

if [[ "$VERBOSE_LEVEL" != "0" ]]; then
    echo "Running Airbender GPU prover (output in $LOG_FILE)..."
else
    echo "Running Airbender GPU prover in quiet mode (output in $LOG_FILE)..."
fi
echo ""

# Run Airbender prover with witness file
# Note: Airbender CLI expects --bin for the binary and --input-file for witness
PROVER_CMD="$AIRBENDER_CLI prove \
    --bin $BIN_FILE \
    --input-file $WITNESS_FILE \
    --output-dir $OUTPUT_DIR \
    --gpu \
    --cycles 2147483648"

if $PROVER_CMD > "$LOG_FILE" 2>&1; then
    echo "=== Proving SUCCEEDED ==="
    echo "Output: $OUTPUT_DIR/"
    ls -la "$OUTPUT_DIR/" 2>/dev/null || true
else
    EXIT_CODE=$?
    echo "=== Proving FAILED (exit code $EXIT_CODE) ==="
    echo ""
    echo "Last 50 lines of log:"
    echo "----------------------------------------"
    tail -50 "$LOG_FILE"
    echo "----------------------------------------"
fi

echo ""
echo "Full log: $LOG_FILE"
