#!/bin/bash
set -e

# Prove ZKsyncOS Ethereum blocks with GPU
# Usage: ./prove-block-gpu.sh [BLOCK_NUMBER]
#
# This script proves Ethereum blocks using ZKsyncOS on the ZisK GPU prover.
# It uses a witness file generated by bench-zisk-cycles.sh to replay oracle data.
#
# The script always performs incremental builds to include any new changes:
# - cargo-zisk binary with GPU support
# - libzisk_witness.so witness library
#
# Precompile Support:
# - U256 delegation (CSR 0x7ca): DISABLED for non-delegation proving measurement (BENCHMARK)
# - Keccak: Native support via CSR 0x800
#
# Prerequisites:
# - Download proving key (see book/building-for-gpu.md)
# - ZKsyncOS ELF built for ZisK
# - Block data in zksync-os/tests/instances/eth_runner/blocks/

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

BLOCK_NUMBER="${1:-24198369}"
ZKSYNCOS_DIR="$REPO_ROOT/zksync-os"
ETH_RUNNER_DIR="$ZKSYNCOS_DIR/tests/instances/eth_runner"
ELF_FILE="$ZKSYNCOS_DIR/zksync_os/zksync_os_zisk.elf"
WITNESS_FILE="$ETH_RUNNER_DIR/${BLOCK_NUMBER}_witness"
OUTPUT_DIR="tmp/zksync-os-prove"

echo "=== ZisK GPU ZKsyncOS Proving Test ==="
echo "Block: $BLOCK_NUMBER"
echo "ELF: $ELF_FILE"
echo "Witness: $WITNESS_FILE"
echo "Output: $OUTPUT_DIR"
echo ""

# Verify ELF exists
if [[ ! -f "$ELF_FILE" ]]; then
    echo "ERROR: ZKsyncOS ELF not found at $ELF_FILE"
    echo "Run: cd zksync-os/zksync_os && ./build.sh --machine zisk"
    exit 1
fi

# Check if witness file exists - generate if needed
if [[ ! -f "$WITNESS_FILE" ]]; then
    echo "Witness file not found. Running bench-zisk-cycles.sh to generate it..."
    echo ""
    ./bench-zisk-cycles.sh "$BLOCK_NUMBER"
    echo ""
    if [[ ! -f "$WITNESS_FILE" ]]; then
        echo "ERROR: Witness file still not found after running benchmark"
        exit 1
    fi
fi
echo "Witness file: $(ls -lh "$WITNESS_FILE" | awk '{print $5}')"
echo ""

# Source Intel OneAPI environment
if [[ -f /opt/intel/oneapi/setvars.sh ]]; then
    source /opt/intel/oneapi/setvars.sh > /dev/null 2>&1
fi

# Set up library paths for Intel OpenMP and Rust std
RUST_STD_PATH="$(rustc --print sysroot)/lib/rustlib/x86_64-unknown-linux-gnu/lib"
export LD_LIBRARY_PATH="$RUST_STD_PATH:/opt/intel/oneapi/compiler/2025.0/lib:${LD_LIBRARY_PATH:-}"
export LIBRARY_PATH="/opt/intel/oneapi/compiler/2025.0/lib:${LIBRARY_PATH:-}"

# Always do incremental builds to include any new changes
PROVER_BINARY="./target/release/cargo-zisk"
WITNESS_LIB="./target/release/libzisk_witness.so"

echo "Building prover with GPU support (incremental)..."
if ! cargo build --release --features gpu 2>&1 | tee /tmp/prover-build.log | tail -10; then
    echo "ERROR: Failed to build prover with GPU support"
    echo "See /tmp/prover-build.log for details"
    exit 1
fi
echo "Prover build complete"
echo ""

echo "Building witness library (incremental)..."
if ! cargo build --release -p zisk-witness --lib 2>&1 | tee /tmp/witness-build.log | tail -5; then
    echo "ERROR: Failed to build witness library"
    echo "See /tmp/witness-build.log for details"
    exit 1
fi
echo "Witness library build complete"
echo ""

mkdir -p "$OUTPUT_DIR"

LOG_FILE="/tmp/prove-block.log"

echo "Running GPU prover (verbose output in $LOG_FILE)..."
echo ""

# Run prover with witness file for oracle data
# Verbose output goes to log file only; terminal shows just errors/final status
if ./target/release/cargo-zisk prove \
    --elf "$ELF_FILE" \
    --witness-file "$WITNESS_FILE" \
    --witness-lib ./target/release/libzisk_witness.so \
    --proving-key ./provingKey \
    --output-dir "$OUTPUT_DIR" \
    --emulator \
    -r \
    -t 4 \
    -v > "$LOG_FILE" 2>&1; then
    echo "=== Proving SUCCEEDED ==="
    echo "Output: $OUTPUT_DIR/"
    ls -la "$OUTPUT_DIR/" 2>/dev/null || true
else
    EXIT_CODE=$?
    echo "=== Proving FAILED (exit code $EXIT_CODE) ==="
    echo ""
    echo "Last 50 lines of log:"
    echo "----------------------------------------"
    tail -50 "$LOG_FILE"
    echo "----------------------------------------"
fi

echo ""
echo "Full log: $LOG_FILE"
