//! Setup pipeline for the recurser-aggregator stage.
//!
//! Drives [`crate::gen_aggregator`] end-to-end to produce the **witness-side**
//! artifacts:
//!
//! - `.circom`, `.r1cs`, `.dat`, witness library (`.so`/`.dylib`)
//! - `.pil`, `.fixed.bin`, `.exec`
//!
//! PIL-derived metadata (`.starkinfo.json`, `.verifierinfo.json`,
//! `.expressionsinfo.json`, `.bin`, `.verifier.bin`, `.const`, `.verkey.*`,
//! `.verifier.rs`) is **not** regenerated by this stage — it's reused from the
//! aggregation-final stage's output.
//!
//! Feature-gated behind `setup` so library users that only need
//! `gen_aggregator` don't pull in the heavy `pil2-stark-setup` chain.
//!
//! Entry points:
//! - [`gen_recurser_aggregator_setup`] / [`RecurserAggregatorConfig`] —
//!   the pipeline itself
//! - [`run_setup_recurser_aggregator`] / [`SetupRecurserAggregatorOptions`] —
//!   the standalone-command wrapper that loads paths/JSON and calls the
//!   pipeline

mod command;
mod proving_key;
mod resolve;

pub use command::{run_setup_recurser_aggregator, SetupRecurserAggregatorOptions};
pub use proving_key::{gen_recurser_aggregator_setup, RecurserAggregatorConfig};
