use std::{collections::HashSet, env, fs};

use zisk_core::{
    decode_and_lower_rv64im32, decode_rv64im32, Rv64imInst, Rv64imOp, StaticRow, StaticRows,
};

#[derive(Clone, Copy)]
struct Case {
    name: &'static str,
    word: u32,
}

const EXPECTED_VALID_CASES: usize = 71;
const EXPECTED_INVALID_CASES: usize = 3;
const EXPECTED_OPCODE_SURFACE: usize = 63;

fn main() {
    let args: Vec<_> = env::args().skip(1).collect();
    if args.is_empty() || args.len() > 3 {
        panic!(
            "usage: cargo run --example aeneas_bridge_cases -- <aeneas-output.lean> [main-output.lean] [cross-output.lean]"
        );
    }
    validate_manifest();
    fs::write(&args[0], aeneas_output()).expect("write Aeneas Lean case file");
    if let Some(path) = args.get(1) {
        fs::write(path, main_output()).expect("write main Lean case file");
    }
    if let Some(path) = args.get(2) {
        fs::write(path, cross_output()).expect("write cross-model Lean case file");
    }
}

fn aeneas_output() -> String {
    let mut out = String::new();
    out.push_str("import Rv64imExtract.Bridge\n\n");
    out.push_str("namespace Rv64imExtract.Bridge.GeneratedCases\n\n");
    out.push_str("/-!\n");
    out.push_str("This file is generated by zisk/core/examples/aeneas_bridge_cases.rs.\n");
    out.push_str("It checks Aeneas-extracted decode/lower behavior for canonical RV64IM\n");
    out.push_str("instruction words. Do not edit by hand.\n");
    out.push_str("-/\n\n");
    out.push_str(&format!("def rv64imValidCaseCount : Nat := {EXPECTED_VALID_CASES}\n"));
    out.push_str(&format!("def rv64imInvalidCaseCount : Nat := {EXPECTED_INVALID_CASES}\n\n"));

    for case in cases() {
        let rows = decode_and_lower_rv64im32(case.word, 0)
            .unwrap_or_else(|| panic!("case {} did not decode: 0x{:08x}", case.name, case.word));
        emit_case(&mut out, case, rows);
    }

    for (name, word) in [
        ("invalid_all_zero", 0x0000_0000),
        ("invalid_all_ones", 0xffff_ffffu32),
        ("invalid_compressed_width", 0x0000_0001),
    ] {
        out.push_str(&format!(
            "theorem decode_lower_{name} :\n    decodeLowerViews 0x{word:08x}#u32 = none := by\n  native_decide\n\n"
        ));
    }

    out.push_str("end Rv64imExtract.Bridge.GeneratedCases\n");
    out
}

fn main_output() -> String {
    let mut out = String::new();
    out.push_str("import ZiskFv.Transpiler.Static\n\n");
    out.push_str("open ZiskFv.Transpiler.Static\n\n");
    out.push_str("namespace ZiskFv.Transpiler.Static.GeneratedAeneasCases\n\n");
    out.push_str("/-!\n");
    out.push_str("This file is generated by zisk/core/examples/aeneas_bridge_cases.rs.\n");
    out.push_str("It checks the main Lean static transpiler on the same encoded-word\n");
    out.push_str("manifest used by the Aeneas extraction spike. Do not edit by hand.\n");
    out.push_str("-/\n\n");
    out.push_str(&format!("def rv64imValidCaseCount : Nat := {EXPECTED_VALID_CASES}\n\n"));

    for case in cases() {
        let inst = decode_rv64im32(case.word, 0)
            .unwrap_or_else(|| panic!("case {} did not decode: 0x{:08x}", case.name, case.word));
        let rows = decode_and_lower_rv64im32(case.word, 0)
            .unwrap_or_else(|| panic!("case {} did not lower: 0x{:08x}", case.name, case.word));
        emit_main_case(&mut out, case, inst, rows);
    }

    out.push_str("end ZiskFv.Transpiler.Static.GeneratedAeneasCases\n");
    out
}

fn cross_output() -> String {
    let mut out = String::new();
    out.push_str("import Rv64imExtract.Bridge\n");
    out.push_str("import ZiskFv.Transpiler.Static\n\n");
    out.push_str("namespace Rv64imExtract.Bridge.CrossModelCases\n\n");
    out.push_str("/-!\n");
    out.push_str("This file is generated by zisk/core/examples/aeneas_bridge_cases.rs.\n");
    out.push_str("It checks, in one Lean 4.28 package, that Aeneas-extracted\n");
    out.push_str("decode/lower rows match the main Lean static transpiler on the same\n");
    out.push_str("encoded-word manifest. Do not edit by hand.\n");
    out.push_str("-/\n\n");
    out.push_str(&format!("def rv64imValidCaseCount : Nat := {EXPECTED_VALID_CASES}\n\n"));
    out.push_str("def rowViewOfStatic (r : ZiskFv.Transpiler.Static.ZiskStaticRow) : RowView :=\n");
    out.push_str("  { paddr := r.paddr\n");
    out.push_str("    op := r.op\n");
    out.push_str("    aSrc := r.aSrc\n");
    out.push_str("    aUseSpImm1 := r.aUseSpImm1\n");
    out.push_str("    aOffsetImm0 := r.aOffsetImm0\n");
    out.push_str("    bSrc := r.bSrc\n");
    out.push_str("    bUseSpImm1 := r.bUseSpImm1\n");
    out.push_str("    bOffsetImm0 := r.bOffsetImm0\n");
    out.push_str("    store := r.store\n");
    out.push_str("    storeOffset := r.storeOffset\n");
    out.push_str("    storePc := r.storePc\n");
    out.push_str("    setPc := r.setPc\n");
    out.push_str("    indWidth := r.indWidth\n");
    out.push_str("    jmpOffset1 := r.jmpOffset1\n");
    out.push_str("    jmpOffset2 := r.jmpOffset2\n");
    out.push_str("    isExternalOp := r.isExternalOp\n");
    out.push_str("    m32 := r.m32 }\n\n");
    out.push_str("def rowsViewOfStatic (rows : List ZiskFv.Transpiler.Static.ZiskStaticRow) : List RowView :=\n");
    out.push_str("  rows.map rowViewOfStatic\n\n");

    for case in cases() {
        let inst = decode_rv64im32(case.word, 0)
            .unwrap_or_else(|| panic!("case {} did not decode: 0x{:08x}", case.name, case.word));
        emit_cross_case(&mut out, case, inst);
    }

    out.push_str("end Rv64imExtract.Bridge.CrossModelCases\n");
    out
}

fn validate_manifest() {
    let cases = cases();
    assert_eq!(
        cases.len(),
        EXPECTED_VALID_CASES,
        "update EXPECTED_VALID_CASES when changing the manifest"
    );

    let mut names = HashSet::new();
    let mut words = HashSet::new();
    let mut opcodes = HashSet::new();
    for case in &cases {
        assert!(names.insert(case.name), "duplicate case name {}", case.name);
        assert!(
            words.insert(case.word),
            "duplicate encoded word for case {}: 0x{:08x}",
            case.name,
            case.word
        );
        let inst = decode_rv64im32(case.word, 0)
            .unwrap_or_else(|| panic!("case {} did not decode: 0x{:08x}", case.name, case.word));
        opcodes.insert(lean_op(inst.op));
    }
    assert_eq!(
        opcodes.len(),
        EXPECTED_OPCODE_SURFACE,
        "manifest stopped covering the expected RV64IM opcode surface"
    );
}

fn emit_case(out: &mut String, case: Case, rows: StaticRows) {
    out.push_str(&format!("def expected_{} : List RowView :=\n", case.name));
    out.push_str("  ");
    emit_rows(out, rows.as_slice());
    out.push_str("\n\n");
    out.push_str(&format!(
        "theorem decode_lower_{} :\n    decodeLowerViews 0x{:08x}#u32 = some expected_{} := by\n  native_decide\n\n",
        case.name, case.word, case.name
    ));
}

fn emit_rows(out: &mut String, rows: &[StaticRow]) {
    out.push('[');
    for (idx, row) in rows.iter().enumerate() {
        if idx > 0 {
            out.push_str(",\n   ");
        }
        emit_row(out, row);
    }
    out.push(']');
}

fn emit_main_case(out: &mut String, case: Case, inst: Rv64imInst, rows: StaticRows) {
    out.push_str(&format!("def expected_{} : List ZiskStaticRow :=\n", case.name));
    out.push_str("  ");
    emit_main_rows(out, rows.as_slice());
    out.push_str("\n\n");
    out.push_str(&format!(
        "theorem transpile_{} :\n    transpile {{ paddr := {}, op := .{}, rd := {}, rs1 := {}, rs2 := {}, imm := {} }} = expected_{} := by\n  native_decide\n\n",
        case.name,
        inst.paddr,
        lean_op(inst.op),
        inst.rd,
        inst.rs1,
        inst.rs2,
        inst.imm,
        case.name
    ));
}

fn emit_cross_case(out: &mut String, case: Case, inst: Rv64imInst) {
    out.push_str(&format!(
        "theorem aeneas_eq_main_static_{} :\n    decodeLowerViews 0x{:08x}#u32 = some (rowsViewOfStatic (ZiskFv.Transpiler.Static.transpile {{ paddr := {}, op := .{}, rd := {}, rs1 := {}, rs2 := {}, imm := {} }})) := by\n  native_decide\n\n",
        case.name,
        case.word,
        inst.paddr,
        lean_op(inst.op),
        inst.rd,
        inst.rs1,
        inst.rs2,
        inst.imm,
    ));
}

fn emit_main_rows(out: &mut String, rows: &[StaticRow]) {
    out.push('[');
    for (idx, row) in rows.iter().enumerate() {
        if idx > 0 {
            out.push_str(",\n   ");
        }
        emit_main_row(out, row);
    }
    out.push(']');
}

fn emit_main_row(out: &mut String, row: &StaticRow) {
    out.push_str(&format!(
        "{{ paddr := {}\n     op := {}\n     aSrc := {}\n     aUseSpImm1 := {}\n     aOffsetImm0 := {}\n     bSrc := {}\n     bUseSpImm1 := {}\n     bOffsetImm0 := {}\n     store := {}\n     storeOffset := {}\n     storePc := {}\n     setPc := {}\n     indWidth := {}\n     jmpOffset1 := {}\n     jmpOffset2 := {}\n     isExternalOp := {}\n     m32 := {} }}",
        row.paddr,
        row.op,
        row.a_src,
        row.a_use_sp_imm1,
        row.a_offset_imm0,
        row.b_src,
        row.b_use_sp_imm1,
        row.b_offset_imm0,
        row.store,
        row.store_offset,
        lean_bool(row.store_pc),
        lean_bool(row.set_pc),
        row.ind_width,
        row.jmp_offset1,
        row.jmp_offset2,
        lean_bool(row.is_external_op),
        lean_bool(row.m32),
    ));
}

fn emit_row(out: &mut String, row: &StaticRow) {
    out.push_str(&format!(
        "{{ paddr := {}\n     op := {}\n     aSrc := {}\n     aUseSpImm1 := {}\n     aOffsetImm0 := {}\n     bSrc := {}\n     bUseSpImm1 := {}\n     bOffsetImm0 := {}\n     store := {}\n     storeOffset := {}\n     storePc := {}\n     setPc := {}\n     indWidth := {}\n     jmpOffset1 := {}\n     jmpOffset2 := {}\n     isExternalOp := {}\n     m32 := {} }}",
        row.paddr,
        row.op,
        row.a_src,
        row.a_use_sp_imm1,
        row.a_offset_imm0,
        row.b_src,
        row.b_use_sp_imm1,
        row.b_offset_imm0,
        row.store,
        row.store_offset,
        lean_bool(row.store_pc),
        lean_bool(row.set_pc),
        row.ind_width,
        row.jmp_offset1,
        row.jmp_offset2,
        lean_bool(row.is_external_op),
        lean_bool(row.m32),
    ));
}

fn lean_op(op: Rv64imOp) -> &'static str {
    match op {
        Rv64imOp::Add => "add",
        Rv64imOp::Sub => "sub",
        Rv64imOp::Sll => "sll",
        Rv64imOp::Slt => "slt",
        Rv64imOp::Sltu => "sltu",
        Rv64imOp::Xor => "xor",
        Rv64imOp::Srl => "srl",
        Rv64imOp::Sra => "sra",
        Rv64imOp::Or => "or",
        Rv64imOp::And => "and",
        Rv64imOp::Addw => "addw",
        Rv64imOp::Subw => "subw",
        Rv64imOp::Sllw => "sllw",
        Rv64imOp::Srlw => "srlw",
        Rv64imOp::Sraw => "sraw",
        Rv64imOp::Addi => "addi",
        Rv64imOp::Slli => "slli",
        Rv64imOp::Slti => "slti",
        Rv64imOp::Sltiu => "sltiu",
        Rv64imOp::Xori => "xori",
        Rv64imOp::Srli => "srli",
        Rv64imOp::Srai => "srai",
        Rv64imOp::Ori => "ori",
        Rv64imOp::Andi => "andi",
        Rv64imOp::Addiw => "addiw",
        Rv64imOp::Slliw => "slliw",
        Rv64imOp::Srliw => "srliw",
        Rv64imOp::Sraiw => "sraiw",
        Rv64imOp::Beq => "beq",
        Rv64imOp::Bne => "bne",
        Rv64imOp::Blt => "blt",
        Rv64imOp::Bge => "bge",
        Rv64imOp::Bltu => "bltu",
        Rv64imOp::Bgeu => "bgeu",
        Rv64imOp::Lb => "lb",
        Rv64imOp::Lbu => "lbu",
        Rv64imOp::Lh => "lh",
        Rv64imOp::Lhu => "lhu",
        Rv64imOp::Lw => "lw",
        Rv64imOp::Lwu => "lwu",
        Rv64imOp::Ld => "ld",
        Rv64imOp::Sb => "sb",
        Rv64imOp::Sh => "sh",
        Rv64imOp::Sw => "sw",
        Rv64imOp::Sd => "sd",
        Rv64imOp::Lui => "lui",
        Rv64imOp::Auipc => "auipc",
        Rv64imOp::Jal => "jal",
        Rv64imOp::Jalr => "jalr",
        Rv64imOp::Fence => "fence",
        Rv64imOp::Mul => "mul",
        Rv64imOp::Mulh => "mulh",
        Rv64imOp::Mulhsu => "mulhsu",
        Rv64imOp::Mulhu => "mulhu",
        Rv64imOp::Mulw => "mulw",
        Rv64imOp::Div => "div",
        Rv64imOp::Divu => "divu",
        Rv64imOp::Divw => "divw",
        Rv64imOp::Divuw => "divuw",
        Rv64imOp::Rem => "rem",
        Rv64imOp::Remu => "remu",
        Rv64imOp::Remw => "remw",
        Rv64imOp::Remuw => "remuw",
    }
}

fn lean_bool(value: bool) -> &'static str {
    if value {
        "true"
    } else {
        "false"
    }
}

fn cases() -> Vec<Case> {
    vec![
        Case { name: "add", word: r_type(0x33, 0, 0, 5, 6, 7) },
        Case { name: "sub", word: r_type(0x33, 0, 32, 5, 6, 7) },
        Case { name: "sll", word: r_type(0x33, 1, 0, 5, 6, 7) },
        Case { name: "slt", word: r_type(0x33, 2, 0, 5, 6, 7) },
        Case { name: "sltu", word: r_type(0x33, 3, 0, 5, 6, 7) },
        Case { name: "xor", word: r_type(0x33, 4, 0, 5, 6, 7) },
        Case { name: "srl", word: r_type(0x33, 5, 0, 5, 6, 7) },
        Case { name: "sra", word: r_type(0x33, 5, 32, 5, 6, 7) },
        Case { name: "or", word: r_type(0x33, 6, 0, 5, 6, 7) },
        Case { name: "and", word: r_type(0x33, 7, 0, 5, 6, 7) },
        Case { name: "addw", word: r_type(0x3b, 0, 0, 5, 6, 7) },
        Case { name: "subw", word: r_type(0x3b, 0, 32, 5, 6, 7) },
        Case { name: "sllw", word: r_type(0x3b, 1, 0, 5, 6, 7) },
        Case { name: "srlw", word: r_type(0x3b, 5, 0, 5, 6, 7) },
        Case { name: "sraw", word: r_type(0x3b, 5, 32, 5, 6, 7) },
        Case { name: "addi", word: i_type(0x13, 0, 5, 6, -1) },
        Case { name: "slli", word: i_shift64(1, 0, 5, 6, 9) },
        Case { name: "slti", word: i_type(0x13, 2, 5, 6, -3) },
        Case { name: "sltiu", word: i_type(0x13, 3, 5, 6, -3) },
        Case { name: "xori", word: i_type(0x13, 4, 5, 6, -3) },
        Case { name: "srli", word: i_shift64(5, 0, 5, 6, 9) },
        Case { name: "srai", word: i_shift64(5, 16, 5, 6, 9) },
        Case { name: "ori", word: i_type(0x13, 6, 5, 6, -3) },
        Case { name: "andi", word: i_type(0x13, 7, 5, 6, -3) },
        Case { name: "addiw", word: i_type(0x1b, 0, 5, 6, -3) },
        Case { name: "slliw", word: i_shift32(1, 0, 5, 6, 9) },
        Case { name: "srliw", word: i_shift32(5, 0, 5, 6, 9) },
        Case { name: "sraiw", word: i_shift32(5, 32, 5, 6, 9) },
        Case { name: "beq", word: b_type(0, 6, 7, 16) },
        Case { name: "bne", word: b_type(1, 6, 7, 16) },
        Case { name: "blt", word: b_type(4, 6, 7, 16) },
        Case { name: "bge", word: b_type(5, 6, 7, 16) },
        Case { name: "bltu", word: b_type(6, 6, 7, 16) },
        Case { name: "bgeu", word: b_type(7, 6, 7, 16) },
        Case { name: "lb", word: i_type(0x03, 0, 5, 6, -8) },
        Case { name: "lbu", word: i_type(0x03, 4, 5, 6, -8) },
        Case { name: "lh", word: i_type(0x03, 1, 5, 6, -8) },
        Case { name: "lhu", word: i_type(0x03, 5, 5, 6, -8) },
        Case { name: "lw", word: i_type(0x03, 2, 5, 6, -8) },
        Case { name: "lwu", word: i_type(0x03, 6, 5, 6, -8) },
        Case { name: "ld", word: i_type(0x03, 3, 5, 6, -8) },
        Case { name: "sb", word: s_type(0, 6, 7, -8) },
        Case { name: "sh", word: s_type(1, 6, 7, -8) },
        Case { name: "sw", word: s_type(2, 6, 7, -8) },
        Case { name: "sd", word: s_type(3, 6, 7, -8) },
        Case { name: "lui", word: u_type(0x37, 5, 0x12345000) },
        Case { name: "auipc", word: u_type(0x17, 5, 0x12345000) },
        Case { name: "auipc_x0", word: u_type(0x17, 0, 0x12345000) },
        Case { name: "jal", word: j_type(5, 2048) },
        Case { name: "jal_x0", word: j_type(0, 2048) },
        Case { name: "jalr_aligned", word: i_type(0x67, 0, 5, 6, 8) },
        Case { name: "jalr_aligned_x0", word: i_type(0x67, 0, 0, 6, 8) },
        Case { name: "jalr_unaligned", word: i_type(0x67, 0, 5, 6, 6) },
        Case { name: "jalr_unaligned_x0", word: i_type(0x67, 0, 0, 6, 6) },
        Case { name: "fence", word: i_type(0x0f, 0, 0, 0, 0) },
        Case { name: "mul", word: r_type(0x33, 0, 1, 5, 6, 7) },
        Case { name: "mulh", word: r_type(0x33, 1, 1, 5, 6, 7) },
        Case { name: "mulhsu", word: r_type(0x33, 2, 1, 5, 6, 7) },
        Case { name: "mulhu", word: r_type(0x33, 3, 1, 5, 6, 7) },
        Case { name: "mulw", word: r_type(0x3b, 0, 1, 5, 6, 7) },
        Case { name: "div", word: r_type(0x33, 4, 1, 5, 6, 7) },
        Case { name: "divu", word: r_type(0x33, 5, 1, 5, 6, 7) },
        Case { name: "divw", word: r_type(0x3b, 4, 1, 5, 6, 7) },
        Case { name: "divuw", word: r_type(0x3b, 5, 1, 5, 6, 7) },
        Case { name: "rem", word: r_type(0x33, 6, 1, 5, 6, 7) },
        Case { name: "remu", word: r_type(0x33, 7, 1, 5, 6, 7) },
        Case { name: "remw", word: r_type(0x3b, 6, 1, 5, 6, 7) },
        Case { name: "remuw", word: r_type(0x3b, 7, 1, 5, 6, 7) },
        Case { name: "add_x0_copy", word: r_type(0x33, 0, 0, 5, 0, 7) },
        Case { name: "addi_nop", word: i_type(0x13, 0, 0, 0, 0) },
        Case { name: "addi_x0_imm_copy", word: i_type(0x13, 0, 5, 0, -1) },
    ]
}

fn r_type(opcode: u32, funct3: u32, funct7: u32, rd: u32, rs1: u32, rs2: u32) -> u32 {
    (funct7 << 25) | (rs2 << 20) | (rs1 << 15) | (funct3 << 12) | (rd << 7) | opcode
}

fn i_type(opcode: u32, funct3: u32, rd: u32, rs1: u32, imm: i32) -> u32 {
    (((imm as u32) & 0xfff) << 20) | (rs1 << 15) | (funct3 << 12) | (rd << 7) | opcode
}

fn i_shift64(funct3: u32, top6: u32, rd: u32, rs1: u32, shamt: u32) -> u32 {
    ((top6 & 0x3f) << 26) | ((shamt & 0x3f) << 20) | (rs1 << 15) | (funct3 << 12) | (rd << 7) | 0x13
}

fn i_shift32(funct3: u32, funct7: u32, rd: u32, rs1: u32, shamt: u32) -> u32 {
    (funct7 << 25) | ((shamt & 0x1f) << 20) | (rs1 << 15) | (funct3 << 12) | (rd << 7) | 0x1b
}

fn s_type(funct3: u32, rs1: u32, rs2: u32, imm: i32) -> u32 {
    let imm = (imm as u32) & 0xfff;
    ((imm >> 5) << 25) | (rs2 << 20) | (rs1 << 15) | (funct3 << 12) | ((imm & 0x1f) << 7) | 0x23
}

fn b_type(funct3: u32, rs1: u32, rs2: u32, imm: i32) -> u32 {
    let imm = (imm as u32) & 0x1fff;
    (((imm >> 12) & 1) << 31)
        | (((imm >> 5) & 0x3f) << 25)
        | (rs2 << 20)
        | (rs1 << 15)
        | (funct3 << 12)
        | (((imm >> 1) & 0xf) << 8)
        | (((imm >> 11) & 1) << 7)
        | 0x63
}

fn u_type(opcode: u32, rd: u32, imm: u32) -> u32 {
    (imm & 0xffff_f000) | (rd << 7) | opcode
}

fn j_type(rd: u32, imm: i32) -> u32 {
    let imm = (imm as u32) & 0x1f_ffff;
    (((imm >> 20) & 1) << 31)
        | (((imm >> 1) & 0x3ff) << 21)
        | (((imm >> 11) & 1) << 20)
        | (((imm >> 12) & 0xff) << 12)
        | (rd << 7)
        | 0x6f
}
