//! Replay processor for pre-recorded oracle responses.
//!
//! This processor replays u32 values that were recorded during witness generation.
//! It's used when executing with a pre-computed witness rather than live oracle data.

use std::sync::atomic::{AtomicUsize, Ordering};

static LAST_READ_POS: AtomicUsize = AtomicUsize::new(0);

/// Replay oracle for 64-bit targets that provides 32-bit witness data.
///
/// The witness file is generated by oracle_provider which stores u32 values:
/// - Each u64 value is split into two u32 values (low first, then high)
/// - response_len indicates the number of u32 reads
///
/// On a 64-bit guest using ZiskOracleBridge:
/// - Each CSR read returns one u32 value (zero-extended to u64)
/// - The guest reads response_len first (as raw u32 count)
/// - The guest then reads response_len u32 values (combining pairs into u64)
/// - The guest divides response_len by 2 to know how many u64 values
///
/// This oracle simply returns u32 values as u64 (zero-extended), matching
/// how ZiskOracleBridge works. No pre-conversion is needed.
///
/// Format of witness file: [response_len1, data1..., response_len2, data2..., ...]
/// where each response_lenN tells how many u32 values follow for that query.
pub struct Replay64Oracle {
    /// Raw u32 values stored as u64 (zero-extended)
    data: Vec<u64>,
    /// Current read position
    position: AtomicUsize,
}

impl Replay64Oracle {
    /// Create from raw bytes (big-endian u32 values).
    ///
    /// Simply parses the u32 values and stores them as u64 (zero-extended).
    /// No conversion is performed - the guest handles the response_len division.
    pub fn from_bytes_be(bytes: &[u8]) -> Self {
        let u32_values: Vec<u32> = bytes
            .chunks_exact(4)
            .map(|chunk| u32::from_be_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]))
            .collect();

        // Store u32 values as u64 (zero-extended)
        let data: Vec<u64> = u32_values.iter().map(|&v| v as u64).collect();

        Self {
            data,
            position: AtomicUsize::new(0),
        }
    }

    /// Read the next u64 value from the replay buffer.
    pub fn read(&self) -> u64 {
        let pos = self.position.fetch_add(1, Ordering::SeqCst);
        if pos < self.data.len() {
            self.data[pos]
        } else {
            0
        }
    }

    /// Write is a no-op for replay (just logs query IDs for debugging).
    pub fn write(&self, _value: u64) {
        // Writes don't affect replay - queries were already processed during recording
    }

    /// Returns the number of u64 values remaining.
    pub fn remaining(&self) -> usize {
        let pos = self.position.load(Ordering::SeqCst);
        self.data.len().saturating_sub(pos)
    }

    /// Returns the total number of u64 values.
    pub fn len(&self) -> usize {
        self.data.len()
    }

    /// Returns true if empty.
    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    /// Get current read position (for debugging)
    pub fn current_position(&self) -> usize {
        self.position.load(Ordering::SeqCst)
    }
}


/// A replay oracle that returns pre-recorded u32 values sequentially.
///
/// During witness generation, all oracle reads are recorded to a `Vec<u32>`.
/// This struct replays those values in the same order.
pub struct ReplayOracle {
    /// Pre-recorded u32 values from witness generation
    data: Vec<u32>,
    /// Current read position
    position: AtomicUsize,
}

impl ReplayOracle {
    /// Create a new replay oracle from pre-recorded data.
    ///
    /// # Arguments
    /// * `data` - The Vec<u32> of pre-recorded oracle reads
    pub fn new(data: Vec<u32>) -> Self {
        Self { data, position: AtomicUsize::new(0) }
    }

    /// Create a replay oracle from raw bytes (little-endian u32 values).
    ///
    /// # Arguments
    /// * `bytes` - Raw bytes containing little-endian u32 values
    pub fn from_bytes(bytes: &[u8]) -> Self {
        let data: Vec<u32> = bytes
            .chunks_exact(4)
            .map(|chunk| u32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]))
            .collect();
        Self::new(data)
    }

    /// Create a replay oracle from raw bytes (big-endian u32 values).
    ///
    /// The zksync-os witness generator outputs big-endian u32 values.
    ///
    /// # Arguments
    /// * `bytes` - Raw bytes containing big-endian u32 values
    pub fn from_bytes_be(bytes: &[u8]) -> Self {
        let data: Vec<u32> = bytes
            .chunks_exact(4)
            .map(|chunk| u32::from_be_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]))
            .collect();
        Self::new(data)
    }

    /// Create a replay oracle from hex-encoded text.
    ///
    /// The zksync-os witness generator outputs u32 values as 8-character hex strings
    /// (big-endian format). Each 8 ASCII chars represents one u32 value.
    ///
    /// # Arguments
    /// * `hex_text` - ASCII hex string where each 8 chars is a big-endian u32
    ///
    /// # Example
    /// ```
    /// use zisk_oracle::processors::ReplayOracle;
    /// let hex = "00000830deadbeef";  // Two u32 values: 2096 and 0xdeadbeef
    /// let oracle = ReplayOracle::from_hex(hex);
    /// assert_eq!(oracle.read(), 0x00000830);
    /// assert_eq!(oracle.read(), 0xdeadbeef);
    /// ```
    pub fn from_hex(hex_text: &str) -> Self {
        let hex_text = hex_text.trim();
        let data: Vec<u32> = hex_text
            .as_bytes()
            .chunks(8)
            .filter_map(|chunk| {
                if chunk.len() == 8 {
                    let s = std::str::from_utf8(chunk).ok()?;
                    u32::from_str_radix(s, 16).ok()
                } else {
                    None
                }
            })
            .collect();

        Self::new(data)
    }

    /// Create a replay oracle from hex-encoded bytes.
    ///
    /// Convenience wrapper that converts bytes to string and calls `from_hex`.
    pub fn from_hex_bytes(bytes: &[u8]) -> Self {
        let hex_text = std::str::from_utf8(bytes).expect("witness file should be valid UTF-8");
        Self::from_hex(hex_text)
    }

    /// Create a replay oracle from 64-bit witness format.
    ///
    /// The zksync-os witness generator stores each 64-bit usize as two 32-bit values
    /// (low first, then high). On a 64-bit target, the guest reads full 64-bit values,
    /// so we need to recombine pairs of u32 into u64.
    ///
    /// The first value (response_len) is kept as-is since it's already a single u32.
    /// Subsequent data values are combined: `(high << 32) | low`.
    ///
    /// # Arguments
    /// * `bytes` - Raw bytes containing big-endian u32 values in the 32-bit split format
    pub fn from_bytes_be_64bit(bytes: &[u8]) -> Self {
        let u32_values: Vec<u32> = bytes
            .chunks_exact(4)
            .map(|chunk| u32::from_be_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]))
            .collect();

        // Recombine for 64-bit target:
        // - First value is response_len (already halved from original 64-bit count)
        // - Response_len tells us how many 32-bit reads the witness recorded
        // - For 64-bit target, we need to:
        //   1. Halve the response_len
        //   2. Combine pairs of u32 into u64 (stored as two u32s: low, high)
        //
        // But wait - the CSR interface returns u64, not u32. Let me rethink.
        // Actually the OracleCallback returns u64. The issue is that the file
        // was recorded with u32 pairs, and we need to return u64.
        //
        // For now, just return the raw u32 values and let the callback handle it.
        // The actual fix needs to be in the callback or a wrapper.

        Self::new(u32_values)
    }

    /// Read the next u32 value from the replay buffer.
    ///
    /// Returns 0 if all values have been consumed.
    pub fn read(&self) -> u32 {
        let pos = self.position.fetch_add(1, Ordering::SeqCst);
        LAST_READ_POS.store(pos, Ordering::SeqCst);
        if pos < self.data.len() {
            self.data[pos]
        } else {
            0
        }
    }

    /// Get the last read position (for debugging)
    pub fn last_read_position() -> usize {
        LAST_READ_POS.load(Ordering::SeqCst)
    }

    /// Write is a no-op for replay oracle (writes were processed during witness generation).
    pub fn write(&self, _value: u32) {
        // Intentionally empty - writes don't affect replay
    }

    /// Returns the number of values remaining to be read.
    pub fn remaining(&self) -> usize {
        let pos = self.position.load(Ordering::SeqCst);
        self.data.len().saturating_sub(pos)
    }

    /// Returns the total number of values in the replay buffer.
    pub fn len(&self) -> usize {
        self.data.len()
    }

    /// Returns true if the replay buffer is empty.
    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_replay_oracle_reads_sequentially() {
        let data = vec![0x12345678, 0xDEADBEEF, 0xCAFEBABE];
        let oracle = ReplayOracle::new(data);

        assert_eq!(oracle.read(), 0x12345678);
        assert_eq!(oracle.read(), 0xDEADBEEF);
        assert_eq!(oracle.read(), 0xCAFEBABE);
        // After exhaustion, returns 0
        assert_eq!(oracle.read(), 0);
    }

    #[test]
    fn test_replay_oracle_from_bytes() {
        // Little-endian bytes for [0x01020304, 0x05060708]
        let bytes = [0x04, 0x03, 0x02, 0x01, 0x08, 0x07, 0x06, 0x05];
        let oracle = ReplayOracle::from_bytes(&bytes);

        assert_eq!(oracle.len(), 2);
        assert_eq!(oracle.read(), 0x01020304);
        assert_eq!(oracle.read(), 0x05060708);
    }

    #[test]
    fn test_replay_oracle_remaining() {
        let data = vec![1, 2, 3];
        let oracle = ReplayOracle::new(data);

        assert_eq!(oracle.remaining(), 3);
        oracle.read();
        assert_eq!(oracle.remaining(), 2);
        oracle.read();
        oracle.read();
        assert_eq!(oracle.remaining(), 0);
    }

    #[test]
    fn test_replay_oracle_write_is_noop() {
        let data = vec![42];
        let oracle = ReplayOracle::new(data);

        // Write should not affect reads
        oracle.write(999);
        assert_eq!(oracle.read(), 42);
    }
}
