//! Replay processor for pre-recorded oracle responses.
//!
//! This processor replays u32 values that were recorded during witness generation.
//! It's used when executing with a pre-computed witness rather than live oracle data.

use std::sync::atomic::{AtomicUsize, Ordering};

static LAST_READ_POS: AtomicUsize = AtomicUsize::new(0);

use std::sync::Mutex;

/// Replay oracle for 64-bit targets that converts 32-bit witness data to 64-bit.
///
/// The witness file is generated by oracle_provider which operates in 32-bit mode:
/// - Each u64 value is split into two u32 values (low first, then high)
/// - response_len indicates the number of u32 reads (not u64s)
///
/// On a 64-bit guest:
/// - Each CSR read returns u32, which is zero-extended to u64
/// - The deserialization expects 1 read per u64 value
/// - response_len should indicate the number of u64 values
///
/// This oracle converts by:
/// 1. Halving response_len values (from # of u32s to # of u64s)
/// 2. Combining pairs of u32 (low, high) into single u64 values
///
/// Format of witness file: [response_len1, data1..., response_len2, data2..., ...]
/// where each response_lenN tells how many u32 values follow for that query.
pub struct Replay64Oracle {
    /// Pre-converted u64 values ready for 64-bit guest
    data: Vec<u64>,
    /// Current read position
    position: AtomicUsize,
}

impl Replay64Oracle {
    /// Create from raw bytes (big-endian u32 values) and convert to 64-bit format.
    ///
    /// Parses the 32-bit witness stream and converts it for 64-bit target:
    /// - Response lengths are halved
    /// - Data pairs (low, high) are combined into u64
    pub fn from_bytes_be(bytes: &[u8]) -> Self {
        let u32_values: Vec<u32> = bytes
            .chunks_exact(4)
            .map(|chunk| u32::from_be_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]))
            .collect();

        // Convert 32-bit stream to 64-bit stream
        let mut data = Vec::new();
        let mut pos = 0;

        while pos < u32_values.len() {
            // Read response_len (number of u32 values following)
            let response_len_32 = u32_values[pos] as usize;
            pos += 1;

            // Convert to 64-bit response_len (number of u64 values)
            let response_len_64 = response_len_32 / 2;
            data.push(response_len_64 as u64);

            eprintln!(
                "[REPLAY64] Converting query: response_len {} u32s -> {} u64s",
                response_len_32, response_len_64
            );

            // Read and combine pairs of u32 into u64
            for i in 0..response_len_64 {
                if pos + 1 >= u32_values.len() {
                    eprintln!(
                        "[REPLAY64] Warning: not enough data for u64 {}, pos={}, len={}",
                        i, pos, u32_values.len()
                    );
                    break;
                }
                let low = u32_values[pos] as u64;
                let high = u32_values[pos + 1] as u64;
                let combined = (high << 32) | low;
                data.push(combined);
                pos += 2;

                // Log some values for debugging
                if i < 5 || i == response_len_64 - 1 {
                    eprintln!(
                        "[REPLAY64]   u64[{}] = 0x{:016x} (low=0x{:08x}, high=0x{:08x})",
                        i, combined, low as u32, high as u32
                    );
                }
            }
        }

        eprintln!(
            "[REPLAY64] Converted {} u32 values to {} u64 values",
            u32_values.len(),
            data.len()
        );

        Self {
            data,
            position: AtomicUsize::new(0),
        }
    }

    /// Read the next u64 value from the replay buffer.
    pub fn read(&self) -> u64 {
        let pos = self.position.fetch_add(1, Ordering::SeqCst);
        if pos < self.data.len() {
            let value = self.data[pos];
            // Log first 50, critical positions, and all reads after 1100
            if pos < 50 || pos % 500 == 0 || pos > 1100 {
                eprintln!("[REPLAY64] read[{}] = 0x{:016x}", pos, value);
            }
            value
        } else {
            eprintln!("[REPLAY64] read[{}] = exhausted (total={})", pos, self.data.len());
            0
        }
    }

    /// Write is logged for debugging.
    pub fn write(&self, value: u64) {
        if value != 0 {
            eprintln!("[REPLAY64] write 0x{:016x}", value);
        }
    }

    /// Returns the number of u64 values remaining.
    pub fn remaining(&self) -> usize {
        let pos = self.position.load(Ordering::SeqCst);
        self.data.len().saturating_sub(pos)
    }

    /// Returns the total number of u64 values.
    pub fn len(&self) -> usize {
        self.data.len()
    }

    /// Returns true if empty.
    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }
}

/// A replay oracle that returns pre-recorded u32 values sequentially.
///
/// During witness generation, all oracle reads are recorded to a `Vec<u32>`.
/// This struct replays those values in the same order.
pub struct ReplayOracle {
    /// Pre-recorded u32 values from witness generation
    data: Vec<u32>,
    /// Current read position
    position: AtomicUsize,
}

impl ReplayOracle {
    /// Create a new replay oracle from pre-recorded data.
    ///
    /// # Arguments
    /// * `data` - The Vec<u32> of pre-recorded oracle reads
    pub fn new(data: Vec<u32>) -> Self {
        Self { data, position: AtomicUsize::new(0) }
    }

    /// Create a replay oracle from raw bytes (little-endian u32 values).
    ///
    /// # Arguments
    /// * `bytes` - Raw bytes containing little-endian u32 values
    pub fn from_bytes(bytes: &[u8]) -> Self {
        let data: Vec<u32> = bytes
            .chunks_exact(4)
            .map(|chunk| u32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]))
            .collect();
        Self::new(data)
    }

    /// Create a replay oracle from raw bytes (big-endian u32 values).
    ///
    /// The zksync-os witness generator outputs big-endian u32 values.
    ///
    /// # Arguments
    /// * `bytes` - Raw bytes containing big-endian u32 values
    pub fn from_bytes_be(bytes: &[u8]) -> Self {
        let data: Vec<u32> = bytes
            .chunks_exact(4)
            .map(|chunk| u32::from_be_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]))
            .collect();
        Self::new(data)
    }

    /// Create a replay oracle from 64-bit witness format.
    ///
    /// The zksync-os witness generator stores each 64-bit usize as two 32-bit values
    /// (low first, then high). On a 64-bit target, the guest reads full 64-bit values,
    /// so we need to recombine pairs of u32 into u64.
    ///
    /// The first value (response_len) is kept as-is since it's already a single u32.
    /// Subsequent data values are combined: `(high << 32) | low`.
    ///
    /// # Arguments
    /// * `bytes` - Raw bytes containing big-endian u32 values in the 32-bit split format
    pub fn from_bytes_be_64bit(bytes: &[u8]) -> Self {
        let u32_values: Vec<u32> = bytes
            .chunks_exact(4)
            .map(|chunk| u32::from_be_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]))
            .collect();

        // Recombine for 64-bit target:
        // - First value is response_len (already halved from original 64-bit count)
        // - Response_len tells us how many 32-bit reads the witness recorded
        // - For 64-bit target, we need to:
        //   1. Halve the response_len
        //   2. Combine pairs of u32 into u64 (stored as two u32s: low, high)
        //
        // But wait - the CSR interface returns u64, not u32. Let me rethink.
        // Actually the OracleCallback returns u64. The issue is that the file
        // was recorded with u32 pairs, and we need to return u64.
        //
        // For now, just return the raw u32 values and let the callback handle it.
        // The actual fix needs to be in the callback or a wrapper.

        Self::new(u32_values)
    }

    /// Read the next u32 value from the replay buffer.
    ///
    /// Returns 0 if all values have been consumed.
    pub fn read(&self) -> u32 {
        let pos = self.position.fetch_add(1, Ordering::SeqCst);
        LAST_READ_POS.store(pos, Ordering::SeqCst);
        if pos < self.data.len() {
            let value = self.data[pos];
            // Log first 20 reads, then every 10000, and around BLOCK_METADATA boundary
            if pos < 20 || pos == 2096 || pos == 2097 || (pos > 0 && pos % 10000 == 0) {
                eprintln!("[REPLAY] read[{}] = 0x{:08x} ({})", pos, value, value);
            }
            value
        } else {
            eprintln!("[REPLAY] read[{}] = exhausted (returning 0)", pos);
            // All data consumed - return 0
            0
        }
    }

    /// Get the last read position (for debugging)
    pub fn last_read_position() -> usize {
        LAST_READ_POS.load(Ordering::SeqCst)
    }

    /// Write is a no-op for replay oracle (writes were processed during witness generation).
    pub fn write(&self, _value: u32) {
        // Intentionally empty - writes don't affect replay
    }

    /// Returns the number of values remaining to be read.
    pub fn remaining(&self) -> usize {
        let pos = self.position.load(Ordering::SeqCst);
        self.data.len().saturating_sub(pos)
    }

    /// Returns the total number of values in the replay buffer.
    pub fn len(&self) -> usize {
        self.data.len()
    }

    /// Returns true if the replay buffer is empty.
    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_replay_oracle_reads_sequentially() {
        let data = vec![0x12345678, 0xDEADBEEF, 0xCAFEBABE];
        let oracle = ReplayOracle::new(data);

        assert_eq!(oracle.read(), 0x12345678);
        assert_eq!(oracle.read(), 0xDEADBEEF);
        assert_eq!(oracle.read(), 0xCAFEBABE);
        // After exhaustion, returns 0
        assert_eq!(oracle.read(), 0);
    }

    #[test]
    fn test_replay_oracle_from_bytes() {
        // Little-endian bytes for [0x01020304, 0x05060708]
        let bytes = [0x04, 0x03, 0x02, 0x01, 0x08, 0x07, 0x06, 0x05];
        let oracle = ReplayOracle::from_bytes(&bytes);

        assert_eq!(oracle.len(), 2);
        assert_eq!(oracle.read(), 0x01020304);
        assert_eq!(oracle.read(), 0x05060708);
    }

    #[test]
    fn test_replay_oracle_remaining() {
        let data = vec![1, 2, 3];
        let oracle = ReplayOracle::new(data);

        assert_eq!(oracle.remaining(), 3);
        oracle.read();
        assert_eq!(oracle.remaining(), 2);
        oracle.read();
        oracle.read();
        assert_eq!(oracle.remaining(), 0);
    }

    #[test]
    fn test_replay_oracle_write_is_noop() {
        let data = vec![42];
        let oracle = ReplayOracle::new(data);

        // Write should not affect reads
        oracle.write(999);
        assert_eq!(oracle.read(), 42);
    }
}
